name = "DataIo"
uuid = "ef35fa6a-3910-11e9-1848-752a35b00f56"
authors = ["Tobias Frilling <tobias@frilling-online.de>"]
version = "0.1.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
